site_name: 'Plots'
site_author: 'Thomas Breloff'

repo_name: 'GitHub'
repo_url: 'https://github.com/JuliaPlots/Plots.jl'

copyright: 'Copyright &copy; 2015-2016 Thomas Breloff'

pages:
  - Home: index.md

  - Getting Started:
      - Installation: install.md
      - Basics: basics.md
      - Tutorial: tutorial.md

  - Manual:
      - Input Data: input_data.md
      - Output: output.md
      - Attributes: attributes.md
      - Layouts: layouts.md
      - Recipes: recipes.md
      - Colors: colors.md
      - Animations: animations.md
      - Backends: backends.md
      - Supported Attributes: supported.md

  - Learning: learning.md
  - Contributing: contributing.md

  - Ecosystem:
      - Overview: ecosystem.md
      - GraphRecipes:
          - Introduction: graphrecipes/introduction.md
          - Examples: graphrecipes/examples.md
          - Attributes: graphrecipes/attributes.md

  - Advanced Topics:
      - Internals: pipeline.md

  - Examples:
      - GR: examples/gr.md
      - PyPlot: examples/pyplot.md
      - PlotlyJS: examples/plotlyjs.md
      - PGFPlots: examples/pgfplots.md
      - UnicodePlots: examples/unicodeplots.md
      - InspectDR: examples/inspectdr.md

docs_dir: 'build'
edit_uri: ../PlotDocs.jl/blob/master/docs/src

# theme: readthedocs
theme: material

extra:
  author:
    github: 'tbreloff'
  palette:
    primary: 'deep orange'
    accent: 'indigo'
  # version: 0.7.4

markdown_extensions:
    - admonition
    - codehilite
    # - mdx_math:
    #     enable_dollar_delimiter: True

extra_javascript: [
     'mathjax-config.js',
     'https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML'
]
